name: Gerar Executável (.exe)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Baixar o Código
      uses: actions/checkout@v4

    - name: Configurar o MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Compilar Forçando exe
      run: msbuild divinity-menu.vcxproj /p:Configuration=Release /p:Platform=x64 /p:OutputType=exe /p:ConfigurationType=Application /p:TargetName=seumenuhere

    - name: Salvar Todos os Arquivos Gerados
      uses: actions/upload-artifact@v4
      with:
        name: executavel-pronto
        path: |
          **/*.exe
          **/*.dll
          **/*.lib
